Implement a pairwise comparison of two segments
AppraiseDev/OCELoT pull request #26
Opened 2021-03-04 18:48 UTC by snukky

In the comparison view, allows for a lightweight annotations of segment pairs with 'A<B', 'A>B' or 'A=B' label.

Changes proposed in the pull request:
- Added `PairwiseRanking` model
- Sending an annotation on a change of the select box using Ajax
- Not using JQuery Slim to have Ajax supported 

To do:
- Showing proper error messages
- Showing which segments already have annotations
- Exporting the annotations
- Optimizations

This PR is made on top of #25.

@AppraiseDev/core-team

2021-03-12 14:50 UTC, cfedermann commented
@snukky: `ModuleNotFoundError: No module named 'pylint_django'` -- spurious issue or did you expect this to break?

2021-03-12 14:52 UTC, cfedermann commented on evaluation/templates/comparison/submission.html
> +                <th>Translations</th>
@snukky: use `Target segments` instead? Or just `Source|Target`?

2021-03-12 14:54 UTC, cfedermann commented on evaluation/views.py
> +    if request.method == "POST" and sub_a_id is None and sub_b_id is None:
@snukky: what's the rationale? Don't you need the submission IDs for storing a comparison result?

2021-03-12 14:54 UTC, cfedermann commented on evaluation/views.py
> +    sub_a_id = int(request.POST.get('submission_a_id'))
@snukky: OK, you don't.

2021-03-12 14:55 UTC, cfedermann commented on ocelot/urls.py
> +    path('compare', compare, name='compare-view'),
@snukky: this really is the `submit-rank-for-comparison` view... The name is confusing.

2021-03-12 14:56 UTC, cfedermann requested changes
@snukky: OK, a last one for discussion today 👍

2021-07-20 20:14 UTC, snukky commented
No, I don't plan to merge this as it might have already diverged too much from the main branch, but I would like to keep this pull request as a draft for having a reminder. Most of the code from this can be re-used once we're back into this enhancement.

2022-07-21 21:16 UTC, closed without merging